-- Sprint 2 / Part 1: employees & drivers (extended), vehicle documents, insurance,
-- driver assignment history, private file metadata, and audit_logs.vehicle_id for the vehicle timeline.
-- Generated by drizzle-kit, then hand-reviewed: renames use RENAME COLUMN and the
-- employee_status enum change maps old values instead of failing on existing rows.
CREATE TYPE "public"."insurance_coverage_type" AS ENUM('THIRD_PARTY', 'COMPREHENSIVE', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."vehicle_document_type" AS ENUM('REGISTRATION', 'INSURANCE', 'LICENSE', 'WARRANTY', 'OWNERSHIP', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."license_type" AS ENUM('PRIVATE', 'PUBLIC', 'HEAVY', 'MOTORCYCLE', 'OTHER');--> statement-breakpoint
CREATE TABLE "files" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"storage_key" text NOT NULL,
	"original_name" text NOT NULL,
	"mime_type" text NOT NULL,
	"size_bytes" integer NOT NULL,
	"sha256" text NOT NULL,
	"uploaded_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "files_storage_key_unique" UNIQUE("storage_key"),
	CONSTRAINT "files_size_ck" CHECK ("files"."size_bytes" > 0)
);
--> statement-breakpoint
CREATE TABLE "insurance_policies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"provider" text NOT NULL,
	"policy_number" text NOT NULL,
	"issue_date" date,
	"expiry_date" date NOT NULL,
	"premium_amount" numeric(14, 2),
	"coverage_type" "insurance_coverage_type" NOT NULL,
	"file_id" uuid,
	"notes" text,
	"superseded_at" timestamp with time zone,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "insurance_dates_ck" CHECK ("insurance_policies"."issue_date" is null or "insurance_policies"."expiry_date" >= "insurance_policies"."issue_date"),
	CONSTRAINT "insurance_premium_ck" CHECK ("insurance_policies"."premium_amount" is null or "insurance_policies"."premium_amount" >= 0)
);
--> statement-breakpoint
CREATE TABLE "vehicle_documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"document_type" "vehicle_document_type" NOT NULL,
	"document_number" text,
	"issue_date" date,
	"expiry_date" date,
	"issuer" text,
	"file_id" uuid,
	"notes" text,
	"superseded_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"deleted_by" uuid,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "vehicle_documents_dates_ck" CHECK ("vehicle_documents"."expiry_date" is null or "vehicle_documents"."issue_date" is null or "vehicle_documents"."expiry_date" >= "vehicle_documents"."issue_date")
);
--> statement-breakpoint
CREATE TABLE "vehicle_driver_history" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"driver_id" uuid NOT NULL,
	"assigned_by" uuid,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"unassigned_by" uuid,
	"unassigned_at" timestamp with time zone
);
--> statement-breakpoint
-- employee_status: ACTIVE/ON_LEAVE/TERMINATED -> ACTIVE/INACTIVE/SUSPENDED/ARCHIVED (data-preserving mapping)
ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT;--> statement-breakpoint
ALTER TYPE "public"."employee_status" RENAME TO "employee_status_old";--> statement-breakpoint
CREATE TYPE "public"."employee_status" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'ARCHIVED');--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "status" SET DATA TYPE "public"."employee_status" USING (
  CASE "status"::text WHEN 'ON_LEAVE' THEN 'INACTIVE' WHEN 'TERMINATED' THEN 'ARCHIVED' ELSE "status"::text END
)::"public"."employee_status";--> statement-breakpoint
ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'::"public"."employee_status";--> statement-breakpoint
DROP TYPE "public"."employee_status_old";--> statement-breakpoint
ALTER TABLE "drivers" ADD COLUMN "license_type" "license_type";--> statement-breakpoint
ALTER TABLE "drivers" ADD COLUMN "license_issue_date" date;--> statement-breakpoint
-- renamed (data preserved)
ALTER TABLE "drivers" RENAME COLUMN "license_expiry" TO "license_expiry_date";--> statement-breakpoint
ALTER TABLE "drivers" ADD COLUMN "notes" text;--> statement-breakpoint
ALTER TABLE "drivers" ADD COLUMN "archived_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "drivers" ADD COLUMN "created_by" uuid;--> statement-breakpoint
-- renamed (data preserved)
ALTER TABLE "employees" RENAME COLUMN "name" TO "full_name";--> statement-breakpoint
ALTER TABLE "employees" ADD COLUMN "national_id" text;--> statement-breakpoint
ALTER TABLE "employees" ADD COLUMN "email" text;--> statement-breakpoint
-- renamed (data preserved)
ALTER TABLE "employees" RENAME COLUMN "start_date" TO "hire_date";--> statement-breakpoint
ALTER TABLE "employees" ADD COLUMN "notes" text;--> statement-breakpoint
ALTER TABLE "employees" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "vehicle_id" uuid;--> statement-breakpoint
ALTER TABLE "files" ADD CONSTRAINT "files_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "files" ADD CONSTRAINT "files_uploaded_by_users_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insurance_policies" ADD CONSTRAINT "insurance_policies_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insurance_policies" ADD CONSTRAINT "insurance_policies_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insurance_policies" ADD CONSTRAINT "insurance_policies_file_id_files_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."files"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insurance_policies" ADD CONSTRAINT "insurance_policies_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_documents" ADD CONSTRAINT "vehicle_documents_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_documents" ADD CONSTRAINT "vehicle_documents_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_documents" ADD CONSTRAINT "vehicle_documents_file_id_files_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."files"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_documents" ADD CONSTRAINT "vehicle_documents_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_documents" ADD CONSTRAINT "vehicle_documents_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_driver_history" ADD CONSTRAINT "vehicle_driver_history_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_driver_history" ADD CONSTRAINT "vehicle_driver_history_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_driver_history" ADD CONSTRAINT "vehicle_driver_history_driver_id_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."drivers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_driver_history" ADD CONSTRAINT "vehicle_driver_history_assigned_by_users_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_driver_history" ADD CONSTRAINT "vehicle_driver_history_unassigned_by_users_id_fk" FOREIGN KEY ("unassigned_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "files_org_idx" ON "files" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "insurance_vehicle_idx" ON "insurance_policies" USING btree ("vehicle_id");--> statement-breakpoint
CREATE INDEX "insurance_org_expiry_idx" ON "insurance_policies" USING btree ("organization_id","expiry_date");--> statement-breakpoint
CREATE UNIQUE INDEX "insurance_org_provider_policy_uq" ON "insurance_policies" USING btree ("organization_id","provider","policy_number");--> statement-breakpoint
CREATE UNIQUE INDEX "insurance_one_current_per_vehicle_uq" ON "insurance_policies" USING btree ("vehicle_id") WHERE "insurance_policies"."superseded_at" is null;--> statement-breakpoint
CREATE INDEX "vehicle_documents_vehicle_type_idx" ON "vehicle_documents" USING btree ("vehicle_id","document_type");--> statement-breakpoint
CREATE INDEX "vehicle_documents_org_expiry_idx" ON "vehicle_documents" USING btree ("organization_id","expiry_date");--> statement-breakpoint
CREATE UNIQUE INDEX "vehicle_documents_one_current_registration_uq" ON "vehicle_documents" USING btree ("vehicle_id") WHERE "vehicle_documents"."document_type" = 'REGISTRATION' and "vehicle_documents"."superseded_at" is null and "vehicle_documents"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "vdh_driver_idx" ON "vehicle_driver_history" USING btree ("driver_id","assigned_at");--> statement-breakpoint
CREATE INDEX "vdh_vehicle_idx" ON "vehicle_driver_history" USING btree ("vehicle_id","assigned_at");--> statement-breakpoint
CREATE UNIQUE INDEX "vdh_one_current_per_vehicle_uq" ON "vehicle_driver_history" USING btree ("vehicle_id") WHERE "vehicle_driver_history"."unassigned_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "vdh_one_current_per_driver_uq" ON "vehicle_driver_history" USING btree ("driver_id") WHERE "vehicle_driver_history"."unassigned_at" is null;--> statement-breakpoint
ALTER TABLE "drivers" ADD CONSTRAINT "drivers_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "employees" ADD CONSTRAINT "employees_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "drivers_org_license_uq" ON "drivers" USING btree ("organization_id","license_number") WHERE "drivers"."license_number" is not null;--> statement-breakpoint
CREATE INDEX "drivers_license_expiry_idx" ON "drivers" USING btree ("organization_id","license_expiry_date");--> statement-breakpoint
CREATE INDEX "employees_org_status_idx" ON "employees" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "audit_vehicle_idx" ON "audit_logs" USING btree ("vehicle_id","created_at");--> statement-breakpoint
ALTER TABLE "employees" ADD CONSTRAINT "employees_org_national_id_uq" UNIQUE("organization_id","national_id");--> statement-breakpoint
ALTER TABLE "drivers" ADD CONSTRAINT "drivers_license_dates_ck" CHECK ("drivers"."license_expiry_date" is null or "drivers"."license_issue_date" is null or "drivers"."license_expiry_date" >= "drivers"."license_issue_date");