/**
 * Permission catalog & built-in role grants — the single source of truth.
 * `npm run db:bootstrap` syncs this into the roles / permissions /
 * role_permissions tables (idempotent), so the DB always matches the code.
 *
 * Scope hierarchy: ALL ⊇ PROJECT ⊇ ASSIGNED
 *   ALL      – every record in the organization
 *   PROJECT  – records in projects the user belongs to (member or manager),
 *              plus records explicitly assigned to the user
 *   ASSIGNED – only records explicitly assigned to the user
 */
export type Scope = "ALL" | "PROJECT" | "ASSIGNED";

export const SCOPE_RANK: Record<Scope, number> = { ASSIGNED: 1, PROJECT: 2, ALL: 3 };

export const PERMISSIONS = {
  "dashboard.view": { module: "dashboard", descriptionAr: "عرض لوحة التحكم" },
  "users.read": { module: "users", descriptionAr: "عرض المستخدمين" },
  "users.manage": { module: "users", descriptionAr: "إنشاء وتعديل المستخدمين وأدوارهم" },
  "roles.read": { module: "roles", descriptionAr: "عرض الأدوار والصلاحيات" },
  "projects.read": { module: "projects", descriptionAr: "عرض المشاريع" },
  "projects.create": { module: "projects", descriptionAr: "إنشاء المشاريع" },
  "projects.update": { module: "projects", descriptionAr: "تعديل بيانات المشاريع" },
  "projects.members.manage": { module: "projects", descriptionAr: "إدارة أعضاء المشاريع" },
  "vehicles.read": { module: "vehicles", descriptionAr: "عرض المركبات" },
  "vehicles.create": { module: "vehicles", descriptionAr: "إضافة المركبات" },
  "vehicles.update": { module: "vehicles", descriptionAr: "تعديل بيانات المركبات" },
  "vehicles.archive": { module: "vehicles", descriptionAr: "أرشفة المركبات" },
  "assignments.read": { module: "assignments", descriptionAr: "عرض إسنادات الآخرين" },
  "assignments.create": { module: "assignments", descriptionAr: "إنشاء الإسنادات" },
  "assignments.manage": { module: "assignments", descriptionAr: "إلغاء وتعديل الإسنادات" },
  "audit.read": { module: "audit", descriptionAr: "عرض سجل التدقيق" },
  "employees.read": { module: "employees", descriptionAr: "عرض الموظفين" },
  "employees.create": { module: "employees", descriptionAr: "إضافة الموظفين" },
  "employees.update": { module: "employees", descriptionAr: "تعديل بيانات الموظفين" },
  "employees.archive": { module: "employees", descriptionAr: "أرشفة الموظفين" },
  "drivers.read": { module: "drivers", descriptionAr: "عرض السائقين" },
  "drivers.create": { module: "drivers", descriptionAr: "إضافة السائقين" },
  "drivers.update": { module: "drivers", descriptionAr: "تعديل بيانات السائقين وإسناد المركبات" },
  "drivers.archive": { module: "drivers", descriptionAr: "أرشفة السائقين" },
  "vehicle_documents.read": { module: "vehicle_documents", descriptionAr: "عرض مستندات المركبات" },
  "vehicle_documents.create": { module: "vehicle_documents", descriptionAr: "إضافة مستندات المركبات" },
  "vehicle_documents.update": { module: "vehicle_documents", descriptionAr: "تعديل مستندات المركبات" },
  "vehicle_documents.delete": { module: "vehicle_documents", descriptionAr: "حذف مستندات المركبات" },
  "registration.read": { module: "registration", descriptionAr: "عرض الاستمارات" },
  "registration.create": { module: "registration", descriptionAr: "إضافة/تجديد الاستمارات" },
  "registration.update": { module: "registration", descriptionAr: "تعديل الاستمارات" },
  "insurance.read": { module: "insurance", descriptionAr: "عرض وثائق التأمين" },
  "insurance.create": { module: "insurance", descriptionAr: "إضافة/تجديد وثائق التأمين" },
  "insurance.update": { module: "insurance", descriptionAr: "تعديل وثائق التأمين" },
  "maintenance.read": { module: "maintenance", descriptionAr: "عرض طلبات الصيانة" },
  "maintenance.create": { module: "maintenance", descriptionAr: "إنشاء طلبات الصيانة" },
  "maintenance.update": { module: "maintenance", descriptionAr: "تنفيذ أعمال الصيانة (فحص، تشخيص، إصلاح)" },
  "maintenance.assign": { module: "maintenance", descriptionAr: "إسناد الفني لطلب الصيانة" },
  "maintenance.approve": { module: "maintenance", descriptionAr: "اعتماد تنفيذ الصيانة" },
  "maintenance.reject": { module: "maintenance", descriptionAr: "رفض طلب الصيانة" },
  "maintenance.handover": { module: "maintenance", descriptionAr: "قبول أو رفض استلام المركبة بعد الإصلاح" },
  "maintenance.close": { module: "maintenance", descriptionAr: "إغلاق طلب الصيانة بعد القبول" },
  "maintenance.quote.read": { module: "maintenance", descriptionAr: "عرض عروض أسعار الصيانة" },
  "maintenance.quote.create": { module: "maintenance", descriptionAr: "إنشاء وتقديم عروض الأسعار" },
  "maintenance.quote.approve": { module: "maintenance", descriptionAr: "اعتماد عروض الأسعار" },
  "maintenance.quote.reject": { module: "maintenance", descriptionAr: "رفض عروض الأسعار" },
  "maintenance.parts.read": { module: "maintenance", descriptionAr: "عرض قطع الغيار" },
  "maintenance.parts.manage": { module: "maintenance", descriptionAr: "إدارة قطع الغيار" },
  "maintenance.labor.read": { module: "maintenance", descriptionAr: "عرض أعمال العمالة" },
  "maintenance.labor.manage": { module: "maintenance", descriptionAr: "إدارة أعمال العمالة" },
  "projects.delete": { module: "projects", descriptionAr: "أرشفة/حذف المشاريع" },
  "members.read": { module: "members", descriptionAr: "عرض أعضاء المشاريع" },
  "members.create": { module: "members", descriptionAr: "إضافة أعضاء للمشاريع" },
  "members.update": { module: "members", descriptionAr: "تعديل أعضاء المشاريع" },
  "members.delete": { module: "members", descriptionAr: "إزالة أعضاء من المشاريع" },
  "users.create": { module: "users", descriptionAr: "إنشاء المستخدمين" },
  "users.update": { module: "users", descriptionAr: "تعديل المستخدمين" },
  "users.delete": { module: "users", descriptionAr: "تعطيل المستخدمين" },
  "drivers.assign": { module: "drivers", descriptionAr: "إسناد السائقين للمركبات" },
  "documents.read": { module: "documents", descriptionAr: "عرض مركز المستندات ومستندات الموظفين" },
  "documents.upload": { module: "documents", descriptionAr: "رفع مستندات الموظفين" },
  "documents.delete": { module: "documents", descriptionAr: "حذف مستندات الموظفين" },
  "finance.read": { module: "finance", descriptionAr: "عرض المالية والمصروفات" },
  "finance.create": { module: "finance", descriptionAr: "تسجيل المصروفات" },
  "finance.approve": { module: "finance", descriptionAr: "اعتماد المصروفات" },
  "finance.reject": { module: "finance", descriptionAr: "رفض المصروفات" },
  "finance.transfer": { module: "finance", descriptionAr: "تسجيل التحويلات البنكية للفواتير" },
  "invoices.read": { module: "invoices", descriptionAr: "عرض الفواتير" },
  "invoices.create": { module: "invoices", descriptionAr: "رفع الفواتير" },
  "invoices.approve": { module: "invoices", descriptionAr: "اعتماد الفواتير" },
  "invoices.reject": { module: "invoices", descriptionAr: "رفض الفواتير" },
  "invoices.upload": { module: "invoices", descriptionAr: "إرفاق ملفات الفواتير" },
  "assignments.update": { module: "assignments", descriptionAr: "تعديل الإسنادات" },
  "assignments.delete": { module: "assignments", descriptionAr: "إلغاء الإسنادات" },
  "reports.read": { module: "reports", descriptionAr: "عرض التقارير" },
  "reports.export": { module: "reports", descriptionAr: "تصدير التقارير" },
  "notifications.read": { module: "notifications", descriptionAr: "عرض الإشعارات الخاصة بالمستخدم" },
  "notifications.manage": { module: "notifications", descriptionAr: "إرسال إشعارات عامة" },
  "accidents.read": { module: "accidents", descriptionAr: "عرض الحوادث" },
  "accidents.create": { module: "accidents", descriptionAr: "تسجيل الحوادث" },
  "accidents.update": { module: "accidents", descriptionAr: "متابعة وإغلاق الحوادث" },
  "violations.read": { module: "violations", descriptionAr: "عرض المخالفات" },
  "violations.create": { module: "violations", descriptionAr: "تسجيل المخالفات" },
  "violations.update": { module: "violations", descriptionAr: "سداد/اعتراض/إلغاء المخالفات" },
  "fuel.read": { module: "fuel", descriptionAr: "عرض عمليات الوقود" },
  "fuel.create": { module: "fuel", descriptionAr: "تسجيل عمليات الوقود" },
  "handover.read": { module: "handover", descriptionAr: "عرض عمليات التسليم والاستلام" },
  "handover.create": { module: "handover", descriptionAr: "إنشاء عمليات التسليم" },
  "handover.manage": { module: "handover", descriptionAr: "مراجعة وإغلاق/إلغاء عمليات التسليم" },
  "gps.read": { module: "gps", descriptionAr: "عرض المواقع والرحلات" },
  "gps.track": { module: "gps", descriptionAr: "إرسال الموقع أثناء الرحلة" },
  "vendors.manage": { module: "vendors", descriptionAr: "إدارة الموردين" },
  "settings.manage": { module: "settings", descriptionAr: "إدارة إعدادات الشركة والنظام" },
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export const ALL_PERMISSION_KEYS = Object.keys(PERMISSIONS) as PermissionKey[];

export type RoleKey =
  | "SUPER_ADMIN"
  | "PROJECT_MANAGER"
  | "FINANCE"
  | "TECHNICAL"
  | "USER"
  | "DRIVER"
  | "VIEWER";

type RoleDef = { nameAr: string; description: string; grants: Partial<Record<PermissionKey, Scope>> };

const allWith = (scope: Scope) =>
  Object.fromEntries(ALL_PERMISSION_KEYS.map((k) => [k, scope])) as Record<PermissionKey, Scope>;

export const ROLES: Record<RoleKey, RoleDef> = {
  SUPER_ADMIN: {
    nameAr: "مدير النظام",
    description: "صلاحيات كاملة على النظام",
    grants: allWith("ALL"),
  },
  PROJECT_MANAGER: {
    nameAr: "مدير مشروع",
    description: "يدير المشاريع المسندة إليه فقط",
    grants: {
      "dashboard.view": "PROJECT",
      "users.read": "PROJECT",
      "projects.read": "PROJECT",
      "projects.update": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicles.update": "PROJECT",
      "assignments.read": "PROJECT",
      "assignments.create": "PROJECT",
      "assignments.manage": "PROJECT",
      "employees.read": "PROJECT",
      "employees.create": "PROJECT",
      "employees.update": "PROJECT",
      "drivers.read": "PROJECT",
      "drivers.create": "PROJECT",
      "drivers.update": "PROJECT",
      "vehicle_documents.read": "PROJECT",
      "vehicle_documents.create": "PROJECT",
      "vehicle_documents.update": "PROJECT",
      "registration.read": "PROJECT",
      "registration.create": "PROJECT",
      "registration.update": "PROJECT",
      "insurance.read": "PROJECT",
      "insurance.create": "PROJECT",
      "insurance.update": "PROJECT",
      // Maintenance: the PM requests, assigns, approves the work and accepts the handover.
      // Quote approval is a FINANCE decision, so the PM does not hold maintenance.quote.approve.
      "maintenance.read": "PROJECT",
      "maintenance.create": "PROJECT",
      "maintenance.update": "PROJECT",
      "maintenance.assign": "PROJECT",
      "maintenance.approve": "PROJECT",
      "maintenance.reject": "PROJECT",
      "maintenance.handover": "PROJECT",
      "maintenance.close": "PROJECT",
      "maintenance.quote.read": "PROJECT",
      "maintenance.quote.create": "PROJECT",
      "maintenance.parts.read": "PROJECT",
      "maintenance.parts.manage": "PROJECT",
      "maintenance.labor.read": "PROJECT",
      "maintenance.labor.manage": "PROJECT",
      "members.read": "PROJECT",
      "drivers.assign": "PROJECT",
      "documents.read": "PROJECT",
      "documents.upload": "PROJECT",
      "finance.read": "PROJECT",
      "finance.create": "PROJECT",
      "invoices.read": "PROJECT",
      "invoices.create": "PROJECT",
      "invoices.upload": "PROJECT",
      "assignments.update": "PROJECT",
      "assignments.delete": "PROJECT",
      "reports.read": "PROJECT",
      "reports.export": "PROJECT",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "accidents.create": "PROJECT",
      "accidents.update": "PROJECT",
      "violations.read": "PROJECT",
      "violations.create": "PROJECT",
      "violations.update": "PROJECT",
      "fuel.read": "PROJECT",
      "fuel.create": "PROJECT",
      "handover.read": "PROJECT",
      "handover.create": "PROJECT",
      "handover.manage": "PROJECT",
      "gps.read": "PROJECT",
      "vendors.manage": "PROJECT",
    },
  },
  FINANCE: {
    nameAr: "المالية",
    description: "مراجعة واعتماد الفواتير والمدفوعات",
    grants: {
      "dashboard.view": "ALL",
      "projects.read": "ALL",
      "vehicles.read": "ALL",
      "vehicle_documents.read": "ALL",
      "registration.read": "ALL",
      "insurance.read": "ALL",
      "maintenance.read": "ALL",
      "maintenance.quote.read": "ALL",
      "maintenance.quote.approve": "ALL",
      "maintenance.quote.reject": "ALL",
      "maintenance.parts.read": "ALL",
      "maintenance.labor.read": "ALL",
      // Finance owns invoices, transfers and expense approval across all projects.
      "finance.read": "ALL",
      "finance.create": "ALL",
      "finance.approve": "ALL",
      "finance.reject": "ALL",
      "finance.transfer": "ALL",
      "invoices.read": "ALL",
      "invoices.create": "ALL",
      "invoices.approve": "ALL",
      "invoices.reject": "ALL",
      "invoices.upload": "ALL",
      "reports.read": "ALL",
      "reports.export": "ALL",
      "notifications.read": "ASSIGNED",
      "accidents.read": "ALL",
      "violations.read": "ALL",
      "violations.update": "ALL",
      "fuel.read": "ALL",
      "documents.read": "ALL",
      "vendors.manage": "ALL",
    },
  },
  TECHNICAL: {
    nameAr: "فني",
    description: "متابعة الصيانة والأعمال الفنية",
    grants: {
      "dashboard.view": "PROJECT",
      "projects.read": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicles.update": "ASSIGNED",
      "vehicle_documents.read": "PROJECT",
      "registration.read": "PROJECT",
      "insurance.read": "PROJECT",
      // Technicians work only on maintenance assigned to them.
      "maintenance.read": "ASSIGNED",
      "maintenance.update": "ASSIGNED",
      "maintenance.quote.read": "ASSIGNED",
      "maintenance.quote.create": "ASSIGNED",
      "maintenance.parts.read": "ASSIGNED",
      "maintenance.parts.manage": "ASSIGNED",
      "maintenance.labor.read": "ASSIGNED",
      "maintenance.labor.manage": "ASSIGNED",
      "invoices.read": "ASSIGNED",
      "invoices.create": "PROJECT",
      "invoices.upload": "ASSIGNED",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "fuel.read": "PROJECT",
      "documents.read": "PROJECT",
    },
  },
  USER: {
    nameAr: "مستخدم",
    description: "مستخدم عادي ضمن مشاريعه",
    grants: {
      "dashboard.view": "PROJECT",
      "projects.read": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicle_documents.read": "PROJECT",
      "registration.read": "PROJECT",
      "maintenance.read": "PROJECT",
      // Users submit invoices/expenses for their projects and see their own.
      "invoices.read": "ASSIGNED",
      "invoices.create": "PROJECT",
      "invoices.upload": "ASSIGNED",
      "finance.read": "ASSIGNED",
      "finance.create": "PROJECT",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "violations.read": "PROJECT",
      "fuel.read": "PROJECT",
      "documents.read": "PROJECT",
    },
  },
  DRIVER: {
    nameAr: "سائق",
    description: "يرى المركبات والمهام المسندة إليه فقط",
    grants: {
      "dashboard.view": "ASSIGNED",
      "vehicles.read": "ASSIGNED",
      // ASSIGNED on employees/drivers = only the driver's own record.
      "employees.read": "ASSIGNED",
      "drivers.read": "ASSIGNED",
      "vehicle_documents.read": "ASSIGNED",
      "registration.read": "ASSIGNED",
      "insurance.read": "ASSIGNED",
      "notifications.read": "ASSIGNED",
      "fuel.read": "ASSIGNED",
      "fuel.create": "ASSIGNED",
      "accidents.read": "ASSIGNED",
      "accidents.create": "ASSIGNED",
      "violations.read": "ASSIGNED",
      "handover.read": "ASSIGNED",
      "gps.track": "ASSIGNED",
    },
  },
  VIEWER: {
    nameAr: "مشاهد",
    description: "عرض فقط ضمن مشاريعه",
    grants: {
      "dashboard.view": "PROJECT",
      "projects.read": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicle_documents.read": "PROJECT",
      "registration.read": "PROJECT",
      "insurance.read": "PROJECT",
      "maintenance.read": "PROJECT",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "violations.read": "PROJECT",
      "fuel.read": "PROJECT",
      "documents.read": "PROJECT",
      "reports.read": "PROJECT",
    },
  },
};

export const ROLE_KEYS = Object.keys(ROLES) as RoleKey[];

export function widerScope(a: Scope | undefined, b: Scope): Scope {
  if (!a) return b;
  return SCOPE_RANK[b] > SCOPE_RANK[a] ? b : a;
}
