import { tr } from "../i18n/index.js";
/**
 * Permission catalog & built-in role grants — the single source of truth.
 * `npm run db:bootstrap` syncs this into the roles / permissions /
 * role_permissions tables (idempotent), so the DB always matches the code.
 *
 * Scope hierarchy: ALL ⊇ PROJECT ⊇ ASSIGNED
 *   ALL      – every record in the organization
 *   PROJECT  – records in projects the user belongs to (member or manager),
 *              plus records explicitly assigned to the user
 *   ASSIGNED – only records explicitly assigned to the user
 */
export type Scope = "ALL" | "PROJECT" | "ASSIGNED";

export const SCOPE_RANK: Record<Scope, number> = { ASSIGNED: 1, PROJECT: 2, ALL: 3 };

export const PERMISSIONS = {
  "dashboard.view": { module: "dashboard", get descriptionAr() { return tr("عرض لوحة التحكم"); } },
  "users.read": { module: "users", get descriptionAr() { return tr("عرض المستخدمين"); } },
  "users.manage": { module: "users", get descriptionAr() { return tr("إنشاء وتعديل المستخدمين وأدوارهم"); } },
  "roles.read": { module: "roles", get descriptionAr() { return tr("عرض الأدوار والصلاحيات"); } },
  "projects.read": { module: "projects", get descriptionAr() { return tr("عرض المشاريع"); } },
  "projects.create": { module: "projects", get descriptionAr() { return tr("إنشاء المشاريع"); } },
  "projects.update": { module: "projects", get descriptionAr() { return tr("تعديل بيانات المشاريع"); } },
  "projects.members.manage": { module: "projects", get descriptionAr() { return tr("إدارة أعضاء المشاريع"); } },
  "vehicles.read": { module: "vehicles", get descriptionAr() { return tr("عرض المركبات"); } },
  "vehicles.create": { module: "vehicles", get descriptionAr() { return tr("إضافة المركبات"); } },
  "vehicles.update": { module: "vehicles", get descriptionAr() { return tr("تعديل بيانات المركبات"); } },
  "vehicles.archive": { module: "vehicles", get descriptionAr() { return tr("أرشفة المركبات"); } },
  "assignments.read": { module: "assignments", get descriptionAr() { return tr("عرض إسنادات الآخرين"); } },
  "assignments.create": { module: "assignments", get descriptionAr() { return tr("إنشاء الإسنادات"); } },
  "assignments.manage": { module: "assignments", get descriptionAr() { return tr("إلغاء وتعديل الإسنادات"); } },
  "audit.read": { module: "audit", get descriptionAr() { return tr("عرض سجل التدقيق"); } },
  "employees.read": { module: "employees", get descriptionAr() { return tr("عرض الموظفين"); } },
  "employees.create": { module: "employees", get descriptionAr() { return tr("إضافة الموظفين"); } },
  "employees.update": { module: "employees", get descriptionAr() { return tr("تعديل بيانات الموظفين"); } },
  "employees.archive": { module: "employees", get descriptionAr() { return tr("أرشفة الموظفين"); } },
  "drivers.read": { module: "drivers", get descriptionAr() { return tr("عرض السائقين"); } },
  "drivers.create": { module: "drivers", get descriptionAr() { return tr("إضافة السائقين"); } },
  "drivers.update": { module: "drivers", get descriptionAr() { return tr("تعديل بيانات السائقين وإسناد المركبات"); } },
  "drivers.archive": { module: "drivers", get descriptionAr() { return tr("أرشفة السائقين"); } },
  "vehicle_documents.read": { module: "vehicle_documents", get descriptionAr() { return tr("عرض مستندات المركبات"); } },
  "vehicle_documents.create": { module: "vehicle_documents", get descriptionAr() { return tr("إضافة مستندات المركبات"); } },
  "vehicle_documents.update": { module: "vehicle_documents", get descriptionAr() { return tr("تعديل مستندات المركبات"); } },
  "vehicle_documents.delete": { module: "vehicle_documents", get descriptionAr() { return tr("حذف مستندات المركبات"); } },
  "registration.read": { module: "registration", get descriptionAr() { return tr("عرض الاستمارات"); } },
  "registration.create": { module: "registration", get descriptionAr() { return tr("إضافة/تجديد الاستمارات"); } },
  "registration.update": { module: "registration", get descriptionAr() { return tr("تعديل الاستمارات"); } },
  "insurance.read": { module: "insurance", get descriptionAr() { return tr("عرض وثائق التأمين"); } },
  "insurance.create": { module: "insurance", get descriptionAr() { return tr("إضافة/تجديد وثائق التأمين"); } },
  "insurance.update": { module: "insurance", get descriptionAr() { return tr("تعديل وثائق التأمين"); } },
  "maintenance.read": { module: "maintenance", get descriptionAr() { return tr("عرض طلبات الصيانة"); } },
  "maintenance.create": { module: "maintenance", get descriptionAr() { return tr("إنشاء طلبات الصيانة"); } },
  "maintenance.update": { module: "maintenance", get descriptionAr() { return tr("تنفيذ أعمال الصيانة (فحص، تشخيص، إصلاح)"); } },
  "maintenance.assign": { module: "maintenance", get descriptionAr() { return tr("إسناد الفني لطلب الصيانة"); } },
  "maintenance.approve": { module: "maintenance", get descriptionAr() { return tr("اعتماد تنفيذ الصيانة"); } },
  "maintenance.reject": { module: "maintenance", get descriptionAr() { return tr("رفض طلب الصيانة"); } },
  "maintenance.handover": { module: "maintenance", get descriptionAr() { return tr("قبول أو رفض استلام المركبة بعد الإصلاح"); } },
  "maintenance.close": { module: "maintenance", get descriptionAr() { return tr("إغلاق طلب الصيانة بعد القبول"); } },
  "maintenance.quote.read": { module: "maintenance", get descriptionAr() { return tr("عرض عروض أسعار الصيانة"); } },
  "maintenance.quote.create": { module: "maintenance", get descriptionAr() { return tr("إنشاء وتقديم عروض الأسعار"); } },
  "maintenance.quote.approve": { module: "maintenance", get descriptionAr() { return tr("اعتماد عروض الأسعار"); } },
  "maintenance.quote.reject": { module: "maintenance", get descriptionAr() { return tr("رفض عروض الأسعار"); } },
  "maintenance.parts.read": { module: "maintenance", get descriptionAr() { return tr("عرض قطع الغيار"); } },
  "maintenance.parts.manage": { module: "maintenance", get descriptionAr() { return tr("إدارة قطع الغيار"); } },
  "maintenance.labor.read": { module: "maintenance", get descriptionAr() { return tr("عرض أعمال العمالة"); } },
  "maintenance.labor.manage": { module: "maintenance", get descriptionAr() { return tr("إدارة أعمال العمالة"); } },
  "projects.delete": { module: "projects", get descriptionAr() { return tr("أرشفة/حذف المشاريع"); } },
  "members.read": { module: "members", get descriptionAr() { return tr("عرض أعضاء المشاريع"); } },
  "members.create": { module: "members", get descriptionAr() { return tr("إضافة أعضاء للمشاريع"); } },
  "members.update": { module: "members", get descriptionAr() { return tr("تعديل أعضاء المشاريع"); } },
  "members.delete": { module: "members", get descriptionAr() { return tr("إزالة أعضاء من المشاريع"); } },
  "users.create": { module: "users", get descriptionAr() { return tr("إنشاء المستخدمين"); } },
  "users.update": { module: "users", get descriptionAr() { return tr("تعديل المستخدمين"); } },
  "users.delete": { module: "users", get descriptionAr() { return tr("تعطيل المستخدمين"); } },
  "drivers.assign": { module: "drivers", get descriptionAr() { return tr("إسناد السائقين للمركبات"); } },
  "documents.read": { module: "documents", get descriptionAr() { return tr("عرض مركز المستندات ومستندات الموظفين"); } },
  "documents.upload": { module: "documents", get descriptionAr() { return tr("رفع مستندات الموظفين"); } },
  "documents.delete": { module: "documents", get descriptionAr() { return tr("حذف مستندات الموظفين"); } },
  "finance.read": { module: "finance", get descriptionAr() { return tr("عرض المالية والمصروفات"); } },
  "finance.create": { module: "finance", get descriptionAr() { return tr("تسجيل المصروفات"); } },
  "finance.approve": { module: "finance", get descriptionAr() { return tr("اعتماد المصروفات"); } },
  "finance.reject": { module: "finance", get descriptionAr() { return tr("رفض المصروفات"); } },
  "finance.transfer": { module: "finance", get descriptionAr() { return tr("تسجيل التحويلات البنكية للفواتير"); } },
  "invoices.read": { module: "invoices", get descriptionAr() { return tr("عرض الفواتير"); } },
  "invoices.create": { module: "invoices", get descriptionAr() { return tr("رفع الفواتير"); } },
  "invoices.approve": { module: "invoices", get descriptionAr() { return tr("اعتماد الفواتير"); } },
  "invoices.reject": { module: "invoices", get descriptionAr() { return tr("رفض الفواتير"); } },
  "invoices.upload": { module: "invoices", get descriptionAr() { return tr("إرفاق ملفات الفواتير"); } },
  "assignments.update": { module: "assignments", get descriptionAr() { return tr("تعديل الإسنادات"); } },
  "assignments.delete": { module: "assignments", get descriptionAr() { return tr("إلغاء الإسنادات"); } },
  "reports.read": { module: "reports", get descriptionAr() { return tr("عرض التقارير"); } },
  "reports.export": { module: "reports", get descriptionAr() { return tr("تصدير التقارير"); } },
  "notifications.read": { module: "notifications", get descriptionAr() { return tr("عرض الإشعارات الخاصة بالمستخدم"); } },
  "notifications.manage": { module: "notifications", get descriptionAr() { return tr("إرسال إشعارات عامة"); } },
  "accidents.read": { module: "accidents", get descriptionAr() { return tr("عرض الحوادث"); } },
  "accidents.create": { module: "accidents", get descriptionAr() { return tr("تسجيل الحوادث"); } },
  "accidents.update": { module: "accidents", get descriptionAr() { return tr("متابعة وإغلاق الحوادث"); } },
  "violations.read": { module: "violations", get descriptionAr() { return tr("عرض المخالفات"); } },
  "violations.create": { module: "violations", get descriptionAr() { return tr("تسجيل المخالفات"); } },
  "violations.update": { module: "violations", get descriptionAr() { return tr("سداد/اعتراض/إلغاء المخالفات"); } },
  "fuel.read": { module: "fuel", get descriptionAr() { return tr("عرض عمليات الوقود"); } },
  "fuel.create": { module: "fuel", get descriptionAr() { return tr("تسجيل عمليات الوقود"); } },
  "handover.read": { module: "handover", get descriptionAr() { return tr("عرض عمليات التسليم والاستلام"); } },
  "handover.create": { module: "handover", get descriptionAr() { return tr("إنشاء عمليات التسليم"); } },
  "handover.manage": { module: "handover", get descriptionAr() { return tr("مراجعة وإغلاق/إلغاء عمليات التسليم"); } },
  "gps.read": { module: "gps", get descriptionAr() { return tr("عرض المواقع والرحلات"); } },
  "gps.track": { module: "gps", get descriptionAr() { return tr("إرسال الموقع أثناء الرحلة"); } },
  "vendors.manage": { module: "vendors", get descriptionAr() { return tr("إدارة الموردين"); } },
  "settings.manage": { module: "settings", get descriptionAr() { return tr("إدارة إعدادات الشركة والنظام"); } },
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export const ALL_PERMISSION_KEYS = Object.keys(PERMISSIONS) as PermissionKey[];

export type RoleKey =
  | "SUPER_ADMIN"
  | "PROJECT_MANAGER"
  | "FINANCE"
  | "TECHNICAL"
  | "USER"
  | "DRIVER"
  | "VIEWER";

type RoleDef = { nameAr: string; description: string; grants: Partial<Record<PermissionKey, Scope>> };

const allWith = (scope: Scope) =>
  Object.fromEntries(ALL_PERMISSION_KEYS.map((k) => [k, scope])) as Record<PermissionKey, Scope>;

export const ROLES: Record<RoleKey, RoleDef> = {
  SUPER_ADMIN: {
    get nameAr() { return tr("مدير النظام"); },
    get description() { return tr("صلاحيات كاملة على النظام"); },
    grants: allWith("ALL"),
  },
  PROJECT_MANAGER: {
    get nameAr() { return tr("مدير مشروع"); },
    get description() { return tr("يدير المشاريع المسندة إليه فقط"); },
    grants: {
      "dashboard.view": "PROJECT",
      "users.read": "PROJECT",
      "projects.read": "PROJECT",
      "projects.update": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicles.update": "PROJECT",
      "assignments.read": "PROJECT",
      "assignments.create": "PROJECT",
      "assignments.manage": "PROJECT",
      "employees.read": "PROJECT",
      "employees.create": "PROJECT",
      "employees.update": "PROJECT",
      "drivers.read": "PROJECT",
      "drivers.create": "PROJECT",
      "drivers.update": "PROJECT",
      "vehicle_documents.read": "PROJECT",
      "vehicle_documents.create": "PROJECT",
      "vehicle_documents.update": "PROJECT",
      "registration.read": "PROJECT",
      "registration.create": "PROJECT",
      "registration.update": "PROJECT",
      "insurance.read": "PROJECT",
      "insurance.create": "PROJECT",
      "insurance.update": "PROJECT",
      // Maintenance: the PM requests, assigns, approves the work and accepts the handover.
      // Quote approval is a FINANCE decision, so the PM does not hold maintenance.quote.approve.
      "maintenance.read": "PROJECT",
      "maintenance.create": "PROJECT",
      "maintenance.update": "PROJECT",
      "maintenance.assign": "PROJECT",
      "maintenance.approve": "PROJECT",
      "maintenance.reject": "PROJECT",
      "maintenance.handover": "PROJECT",
      "maintenance.close": "PROJECT",
      "maintenance.quote.read": "PROJECT",
      "maintenance.quote.create": "PROJECT",
      "maintenance.parts.read": "PROJECT",
      "maintenance.parts.manage": "PROJECT",
      "maintenance.labor.read": "PROJECT",
      "maintenance.labor.manage": "PROJECT",
      "members.read": "PROJECT",
      "drivers.assign": "PROJECT",
      "documents.read": "PROJECT",
      "documents.upload": "PROJECT",
      "finance.read": "PROJECT",
      "finance.create": "PROJECT",
      "invoices.read": "PROJECT",
      "invoices.create": "PROJECT",
      "invoices.upload": "PROJECT",
      "assignments.update": "PROJECT",
      "assignments.delete": "PROJECT",
      "reports.read": "PROJECT",
      "reports.export": "PROJECT",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "accidents.create": "PROJECT",
      "accidents.update": "PROJECT",
      "violations.read": "PROJECT",
      "violations.create": "PROJECT",
      "violations.update": "PROJECT",
      "fuel.read": "PROJECT",
      "fuel.create": "PROJECT",
      "handover.read": "PROJECT",
      "handover.create": "PROJECT",
      "handover.manage": "PROJECT",
      "gps.read": "PROJECT",
      "vendors.manage": "PROJECT",
    },
  },
  FINANCE: {
    get nameAr() { return tr("المالية"); },
    get description() { return tr("مراجعة واعتماد الفواتير والمدفوعات"); },
    grants: {
      "dashboard.view": "ALL",
      "projects.read": "ALL",
      "vehicles.read": "ALL",
      "vehicle_documents.read": "ALL",
      "registration.read": "ALL",
      "insurance.read": "ALL",
      "maintenance.read": "ALL",
      "maintenance.quote.read": "ALL",
      "maintenance.quote.approve": "ALL",
      "maintenance.quote.reject": "ALL",
      "maintenance.parts.read": "ALL",
      "maintenance.labor.read": "ALL",
      // Finance owns invoices, transfers and expense approval across all projects.
      "finance.read": "ALL",
      "finance.create": "ALL",
      "finance.approve": "ALL",
      "finance.reject": "ALL",
      "finance.transfer": "ALL",
      "invoices.read": "ALL",
      "invoices.create": "ALL",
      "invoices.approve": "ALL",
      "invoices.reject": "ALL",
      "invoices.upload": "ALL",
      "reports.read": "ALL",
      "reports.export": "ALL",
      "notifications.read": "ASSIGNED",
      "accidents.read": "ALL",
      "violations.read": "ALL",
      "violations.update": "ALL",
      "fuel.read": "ALL",
      "documents.read": "ALL",
      "vendors.manage": "ALL",
    },
  },
  TECHNICAL: {
    get nameAr() { return tr("فني"); },
    get description() { return tr("متابعة الصيانة والأعمال الفنية"); },
    grants: {
      "dashboard.view": "PROJECT",
      "projects.read": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicles.update": "ASSIGNED",
      "vehicle_documents.read": "PROJECT",
      "registration.read": "PROJECT",
      "insurance.read": "PROJECT",
      // Technicians work only on maintenance assigned to them.
      "maintenance.read": "ASSIGNED",
      "maintenance.update": "ASSIGNED",
      "maintenance.quote.read": "ASSIGNED",
      "maintenance.quote.create": "ASSIGNED",
      "maintenance.parts.read": "ASSIGNED",
      "maintenance.parts.manage": "ASSIGNED",
      "maintenance.labor.read": "ASSIGNED",
      "maintenance.labor.manage": "ASSIGNED",
      "invoices.read": "ASSIGNED",
      "invoices.create": "PROJECT",
      "invoices.upload": "ASSIGNED",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "fuel.read": "PROJECT",
      "documents.read": "PROJECT",
    },
  },
  USER: {
    get nameAr() { return tr("مستخدم"); },
    get description() { return tr("مستخدم عادي ضمن مشاريعه"); },
    grants: {
      "dashboard.view": "PROJECT",
      "projects.read": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicle_documents.read": "PROJECT",
      "registration.read": "PROJECT",
      "maintenance.read": "PROJECT",
      // Users submit invoices/expenses for their projects and see their own.
      "invoices.read": "ASSIGNED",
      "invoices.create": "PROJECT",
      "invoices.upload": "ASSIGNED",
      "finance.read": "ASSIGNED",
      "finance.create": "PROJECT",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "violations.read": "PROJECT",
      "fuel.read": "PROJECT",
      "documents.read": "PROJECT",
    },
  },
  DRIVER: {
    get nameAr() { return tr("سائق"); },
    get description() { return tr("يرى المركبات والمهام المسندة إليه فقط"); },
    grants: {
      "dashboard.view": "ASSIGNED",
      "vehicles.read": "ASSIGNED",
      // ASSIGNED on employees/drivers = only the driver's own record.
      "employees.read": "ASSIGNED",
      "drivers.read": "ASSIGNED",
      "vehicle_documents.read": "ASSIGNED",
      "registration.read": "ASSIGNED",
      "insurance.read": "ASSIGNED",
      "notifications.read": "ASSIGNED",
      "fuel.read": "ASSIGNED",
      "fuel.create": "ASSIGNED",
      "accidents.read": "ASSIGNED",
      "accidents.create": "ASSIGNED",
      "violations.read": "ASSIGNED",
      "handover.read": "ASSIGNED",
      "gps.track": "ASSIGNED",
    },
  },
  VIEWER: {
    get nameAr() { return tr("مشاهد"); },
    get description() { return tr("عرض فقط ضمن مشاريعه"); },
    grants: {
      "dashboard.view": "PROJECT",
      "projects.read": "PROJECT",
      "vehicles.read": "PROJECT",
      "vehicle_documents.read": "PROJECT",
      "registration.read": "PROJECT",
      "insurance.read": "PROJECT",
      "maintenance.read": "PROJECT",
      "notifications.read": "ASSIGNED",
      "accidents.read": "PROJECT",
      "violations.read": "PROJECT",
      "fuel.read": "PROJECT",
      "documents.read": "PROJECT",
      "reports.read": "PROJECT",
    },
  },
};

export const ROLE_KEYS = Object.keys(ROLES) as RoleKey[];

export function widerScope(a: Scope | undefined, b: Scope): Scope {
  if (!a) return b;
  return SCOPE_RANK[b] > SCOPE_RANK[a] ? b : a;
}
